namespace ActoEngine.WebApi.Features.Patcher;

public static class PatcherQueries
{
    public const string GetPatchConfig = @"
        SELECT ProjectRootPath, ViewDirPath, ScriptDirPath, PatchDownloadPath
        FROM Projects
        WHERE ProjectId = @ProjectId";

    public const string UpdatePatchConfig = @"
        UPDATE Projects
        SET ProjectRootPath = @ProjectRootPath,
            ViewDirPath = @ViewDirPath,
            ScriptDirPath = @ScriptDirPath,
            PatchDownloadPath = @PatchDownloadPath
        WHERE ProjectId = @ProjectId";

    public const string GetLatestPatch = @"
        SELECT TOP 1 ph.PatchId, ph.ProjectId, ph.PageName, ph.DomainName, ph.SpNames, ph.PatchName,
                       ph.IsNewPage, ph.PatchFilePath, ph.GeneratedAt, ph.GeneratedBy, ph.Status
        FROM PatchHistory ph
        JOIN PatchHistoryPages php ON ph.PatchId = php.PatchId
        WHERE ph.ProjectId = @ProjectId
          AND php.DomainName = @DomainName
          AND php.PageName = @PageName
        ORDER BY ph.GeneratedAt DESC";

    public const string GetPatchHistory = @"
        SELECT ph.PatchId, ph.ProjectId, ph.PageName, ph.DomainName, ph.SpNames, ph.PatchName,
                 ph.IsNewPage, ph.PatchFilePath, ph.GeneratedAt, ph.GeneratedBy, ph.Status,
                 php.DomainName AS PageDomain, php.PageName AS PagePage, php.IsNewPage AS PageIsNew
        FROM PatchHistory ph
        LEFT JOIN PatchHistoryPages php ON ph.PatchId = php.PatchId
        WHERE ph.ProjectId = @ProjectId
        ORDER BY ph.GeneratedAt DESC";

    public const string InsertPatchHistory = @"
        INSERT INTO PatchHistory
            (ProjectId, PageName, DomainName, SpNames, PatchName, IsNewPage, PatchFilePath, GeneratedAt, GeneratedBy, Status)
        VALUES
            (@ProjectId, @PageName, @DomainName, @SpNames, @PatchName, @IsNewPage, @PatchFilePath, GETUTCDATE(), @GeneratedBy, @Status);
        SELECT SCOPE_IDENTITY();";

    public const string InsertPatchHistoryPages = @"
        INSERT INTO PatchHistoryPages (PatchId, DomainName, PageName, IsNewPage)
        VALUES (@PatchId, @DomainName, @PageName, @IsNewPage)";

    public const string GetPatchById = @"
        SELECT PatchId, ProjectId, PageName, DomainName, SpNames, PatchName,
                 IsNewPage, PatchFilePath, GeneratedAt, GeneratedBy, Status
        FROM PatchHistory
        WHERE PatchId = @PatchId";

    public const string GetSpOutboundDependencies = @"
        SELECT d.TargetId AS TableId, t.TableName, t.SchemaName
        FROM Dependencies d
        JOIN TablesMetadata t ON d.TargetId = t.TableId AND t.ProjectId = d.ProjectId AND t.IsDeleted = 0
        WHERE d.ProjectId = @ProjectId
          AND d.SourceType = 'SP'
          AND d.SourceId = @SpId
          AND d.TargetType = 'TABLE'";

    public const string GetSpProcedureDependencies = @"
        SELECT d.TargetId AS SpId, s.ProcedureName, s.SchemaName
        FROM Dependencies d
        JOIN SpMetadata s ON d.TargetId = s.SpId AND s.ProjectId = d.ProjectId AND s.IsDeleted = 0
        WHERE d.ProjectId = @ProjectId
          AND d.SourceType = 'SP'
          AND d.SourceId = @SpId
          AND d.TargetType = 'SP'";

    public const string GetSpColumnDependencies = @"
        SELECT
                d.TargetId AS ColumnId,
                c.ColumnName,
                t.TableId,
                t.TableName,
                t.SchemaName
        FROM Dependencies d
        JOIN ColumnsMetadata c ON d.TargetId = c.ColumnId
        JOIN TablesMetadata t ON c.TableId = t.TableId AND t.ProjectId = d.ProjectId AND t.IsDeleted = 0
        WHERE d.ProjectId = @ProjectId
          AND d.SourceType = 'SP'
          AND d.SourceId = @SpId
          AND d.TargetType = 'COLUMN'";

    public const string MenuPermissionScriptTemplate = @"-- =============================================
-- Menu & Permission Script (New Page)
-- Page: {SafePageName} | Domain: {SafeDomainName}
-- Generated by ActoEngine on {Timestamp}
-- =============================================

DECLARE @TableName SYSNAME = 'Common_MenuMas'
DECLARE @WhereClause NVARCHAR(MAX) = 'WHERE [Action] = ''{SafePageName}'''
DECLARE @Cols NVARCHAR(MAX), @ColsValues NVARCHAR(MAX), @SQL NVARCHAR(MAX)

-- Build column list (excludes IDENTITY columns)
SELECT @Cols = STUFF((
    SELECT ',' + QUOTENAME(COLUMN_NAME)
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = @TableName
      AND COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA + '.' + TABLE_NAME), COLUMN_NAME, 'IsIdentity') = 0
    ORDER BY ORDINAL_POSITION
    FOR XML PATH(''), TYPE
).value('.', 'NVARCHAR(MAX)'),1,1,'')

-- Build value expressions
SELECT @ColsValues = STUFF((
    SELECT ' + '','' + ISNULL('''''''' + 
           REPLACE(CAST(' + QUOTENAME(COLUMN_NAME) + ' AS NVARCHAR(MAX)),'''''''','''''''''''') + 
           '''''''',''NULL'')'
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = @TableName
      AND COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA + '.' + TABLE_NAME), COLUMN_NAME, 'IsIdentity') = 0
    ORDER BY ORDINAL_POSITION
    FOR XML PATH(''), TYPE
).value('.', 'NVARCHAR(MAX)'),1,9,'')

-- Generate conditional INSERT with auto-permission
SET @SQL = '
SELECT ''IF NOT EXISTS (SELECT 1 FROM ' + @TableName + ' ' + 
    REPLACE(@WhereClause, '''', '''''') + ') ' + 
    'BEGIN ' + 
        'INSERT INTO ' + @TableName + '(' + @Cols + ') VALUES ('' + ' + @ColsValues + ' + ''); ' +
        'INSERT INTO Security_UserPermission 
            (UserGroupId, MenuId, IsView, IsAdd, IsUpdate, IsDelete, IsDownload, IsDisableIpLock) ' +
        'SELECT UserGroupId, SCOPE_IDENTITY(), 1, 1, 1, 1, 1, 1 ' + 
        'FROM Security_UserAccessGroups WHERE UserGroupName = ''''Administration''''; ' +
    'END''
FROM ' + @TableName + ' ' + @WhereClause

EXEC(@SQL)";
}
